# fly.toml file generated for summer-thunder-4876 on 2023-02-24T16:29:14-08:00

app = "summer-thunder-4876"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "ghcr.io/superfly/fly-log-shipper:latest"

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8686
